development:
  adapter: mysql2
  database: datatables_talk_development
  pool: 8
  username: root
  password: josh123
test:
  adapter: mysql2
  database: datatables_talk_test
  pool: 5
  timeout: 5000
  username: root
  password: josh123

production:
  adapter: mysql2
  database: datatables_talk_production
  pool: 5
  timeout: 5000
  username: root
  password: josh123
